# .github/workflows/ci.yml
name: IRIS DVC + MLflow CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test_and_report:
    runs-on: ubuntu-latest
    
    # REQUIRED: Grant token permissions for CML to post the PR comment
    permissions:
      contents: write
      pull-requests: write
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # ----------------------------------------------------
      # 1. SETUP CORE ENVIRONMENT & AUTH
      # ----------------------------------------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (DVC, MLflow, Pytest)
        run: |
          sudo apt-get update
          # Use -s flag to capture output from Python prints (useful for debugging)
          pip install -r requirements.txt
          
      - name: Set Google Cloud Credentials (For DVC Data Pull)
        uses: google-github-actions/auth@v2
        with:
          # This secret allows the runner to access the GCS bucket for DVC
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # ----------------------------------------------------
      # 2. DVC DATA PULL
      # ----------------------------------------------------
      - name: Configure DVC for GCS Remote
        run: |
          dvc remote add -d gcs_bucket gs://week-2-mlops-bucket/dvc_remote --force
          dvc config core.no_scm true

      - name: Set Google Cloud Credentials
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: DVC Pull Data and Model
        run: |
          # Use --force to prevent issues with files generated/left over by the runner
          dvc pull data/V3_augmented.csv.dvc --force
          
      - name: Set MLflow Tracking URI and Authenticate
        env:
            # 1. Set the Tracking URI to point to the local metadata
            MLFLOW_TRACKING_URI: 'file://${{ github.workspace }}/mlruns' 

            # 2. CRITICAL: Pass the GCS Artifact URI so MLflow knows how to resolve the model payload
            MLFLOW_GCS_ARTIFACT_URI: 'gs://week-2-mlflow-artifacts-bucket/iris_artifacts'
          
        run: |
            # This export isn't always strictly needed but reinforces the artifact location
            export MLFLOW_TRACKING_URI="${{ env.MLFLOW_TRACKING_URI }}"

            # You must also inform MLflow of the GCS artifact location.
            # While artifact_location is set during tracking, explicitly setting it as an
            # environment variable can sometimes resolve ambiguity in different MLflow versions.
            echo "MLFLOW_ARTIFACT_LOCATION=${{ env.MLFLOW_GCS_ARTIFACT_URI }}" >> $GITHUB_ENV

            echo "MLflow tracking set up. Model artifacts will be retrieved from GCS."



      # ----------------------------------------------------
      # 3. TESTING
      # ----------------------------------------------------
      - name: Run Pytest Validation and Evaluation Tests
        # The test script fetches the model from the MLflow Registry using the URI set above.
        run: pytest tests/test_pipeline.py -s

      # ----------------------------------------------------
      # 4. CML SETUP AND REPORTING
      # ----------------------------------------------------
      - name: Setup CML ðŸ› ï¸
        uses: iterative/setup-cml@v2
        
      - name: Create CML Sanity Report
        if: github.event_name == 'pull_request'
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## CI/CD Pipeline Status Report ðŸ¤–" > report.md
          echo "" >> report.md
          echo "### Data and Model DVC/MLflow Status" >> report.md
          echo "- **Input Data (DVC):** \`data/V3_augmented.csv\` (Pulled from GCS)" >> report.md
          echo "- **Model (MLflow):** Latest registered model fetched from Registry." >> report.md
          echo "" >> report.md
          echo "### Test Results (pytest)" >> report.md
          echo "- **Data Validation:** âœ… Passed" >> report.md
          echo "- **Model Sanity Check:** âœ… Passed" >> report.md
          echo "" >> report.md
          echo "CI pipeline successfully verified data via DVC and model via MLflow Registry." >> report.md
          
          # Use the CML command to post the report as a comment on the Pull Request
          cml comment create report.md
